name: Docker Image CI meta test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: name/app
